# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.7"
  - "3.6"
  - "3.5"
  - "2.7"

install: pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
#script: python setup.py test
script: coverage run setup.py test

# Command for online test coverage analysis
before_install:
  pip install codecov

after_success:
  codecov
